<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type">
<title>MA03 Egyidejűség</title>
</head> <?php  include "../../h.php"; $_SERVER['REQUEST_URI']; $pa = $_SERVER['REQUEST_URI']; if (isset($_GET['pap']))				$pap = $_GET['pap']; if (isset($_GET['par']))				$par = $_GET['par']; ?> <body>

<p>ÉS HOGY A DOLOG MÉG B3NYOLULTABB LEGYEN: a "látott" és megtapasztalt (térbeli kiterjedéssel rendelkező) valóságot mi valóban időszeletekben látjuk és gondoljuk el. Az <b>1m/s </b>fénysebesség helyett most képzeljünk el <b>1m/év</b> fénysebességet, és a kétszázméteres (azaz kétszázfényéves) rakétában minden méterre ültessünk le egy embert, jobban mondva egy egynapos csecsemőt (ahhoz azonban, hogy az "ültetés" egyidejű legyen, az űrhajó közepéből egy indító "<b>A</b>" fényjelet kell felvillantani: az űrhajó közepén száz évet kell várnunk az űrhajós "beültetésével", kilencvenkilenc évet az első kétoldali csecsemőpár elhelyezésével, kilencvenet a tizedik párral, az utolsó két legszélső csecsemőt pedig az "<b>A</b>"  jel beérkezésének pillanatában ültetjük egynaposan a helyére). <p><p><p><p>

Minden "születés" járjon egy születési "<b>B</b>" fényfelvillanással: az űrhajós egy év múlva meglátja az első csecsemőpár megszületését ("<b>B<sub>-1</sub></b>" és "<b>B<sub>+1</sub></b>" ), még egy év múlva a következő csecsemőpárt ("<b>B<sub>-2</sub></b>" és "<b>B<sub>+2</sub></b>" ), száz év elteltével a két legszélső csecsemő születését is meglátja ("<b>B<sub>-100</sub></b>" és "<b>B<sub>+100</sub></b>" ).<p>

A rakéta közepén ülő űrhajós-csecsemő villantson meg egy ellenőrző "<b>C</b>" vakut még élete első napján: a fény mindkét irányba kiterjed, visszavert fényében két év elteltével meglátja az első két egyéves "csecsemőt" ("<b>C<sub>-1</sub></b>" és "<b>C<sub>+1</sub></b>" ), négy év elteltével meglátja a másik két  "csecsemőt" kétéves korban ("<b>C<sub>-2</sub></b>" és "<b>C<sub>+2</sub></b>" ), és így tovább a századik emberünkig mindkét oldalra, akiket százéves korában pillant meg ("<b>C<sub>-100</sub></b>" és "<b>C<sub>+100</sub></b>", eddigre az űrhajós kétszázéves lett). A fény állandó sebességéből és a látottak alapján az űrhajós arra következtet, hogy utastársaival egyidőben születtek meg a kétszáz fényév hosszú rakétában.</p>
<p> </p>
<p>A Földről nézve a rakéta csak két méter hosszú: a közepéből induló indító "<b>A</b>" fényjel fél év elteltével ütközik a majdnem fénysebességgel felénk tartó űrhajó farával és máris megszületett a "kormányos" (akit további fél év elteltével meg is pillantunk, "<b>A<sub>-100</sub></b>=<b>B<sub>-100</sub></b>"). Az első szomszédja, akihez ez a jel ugyan két nappal előbb érkezett be, de egy évet köteles  volt várni (hogy az űrhajón mindannyian egyidőben szülessenek meg), ami a földi vonatkozási rendszerben száz év, mely idő alatt a kétméteres űrhajó száz méterrel (fényévvel) arrább mozdult, és így a száz évvel később született "kormányossegéd" születését kettőszáz év elteltével látjuk meg a Földön ("<b>B<sub>-99</sub></b>"). Az űrhajós születési fényjele (aki száz évet, a mi rendszerünkben tízezer évet várt a "megszületéssel", mialatt  az űrhajó tízezer méterrel arrébb mozdult) húszezer év után érkezik meg hozzánk (mert a születési "<b>B<sub>0</sub></b>" fényjelnek tízezer métert kell megtennie visszafelé). Mivel a hajó orra majdnem fénysebességgel (pontosan: v=0.99995c) szökik a hajó közepéből indított indító "<b>A</b>"  fényjel elől, úgy az indító jel húszezer év elteltével éri utól a hajó orrát (fél fényév előnyt a fény 10000 év alatt hoz be 0.99995 szökési sebesség esetén), és így a legelől ülő újszülöttet negyvenezer év után látjuk meg a Földről bámészkodva. A fény állandó sebességéből és a látottak alapján a földi megfigyelő arra következtet, hogy legelsőnek a kormányos született meg, majd kétszázévente megjelennek az egyre előrébb ülők, akik száz-száz év késéssel születtek, utolsónak pedig negyvenezer év késéssel megjelen a húszezer év késéssel született  legelől ülő emberünk is a két fényév hosszú rakéta orrában.</p>

<p>

Az űrhajó közepén ülő űrhajós ellenőrző "<b>C</b>"  vakuzását (mely a tízezredik évben indul tízezer fényév távolságban a Földtől) a Földről úgy látnánk, hogy a rakéta csak két méter hosszú és minden centiméteren ül egy alaposan ellaposodott ember (valójában még nem születtek meg mindannyian a földi megfigyelő szerint, csak az űrhajós mögött ülők vannak már a helyükön):  a vaku fénye legelőször az űrhajós mögött ülő féléves emberkéről verődne vissza másnap (mert ő is rohan a rakétával együtt a kontroll "<b>C</b>" fénysugár felé szinte fénysebességgel, így az egy centi helyett az ellenőrző "<b>C</b>" fénysugár csak fél centit kell hogy megtegyen, ami a méter kétszázad réssze, azaz az év kétszázad része, ami kb. 40 óra). Igenám, de mivel mindez tízezer fényévre történik tőlünk, csak tízezer év elteltével érkezik meg hozzánk az ellenőrző "<b>C<sub>-1</sub></b>" fénysugár az egyéves csecsemőről. Mivel azonban ez a fénysugár egyenesen továbbhaladt az űrhajó hátsó része, azutá meg a távoli Föld felé, egyidőben meg fogjuk látni a kétéves  csecsemő "<b>C<sub>-2</sub></b>", a hároméves csecsemő "<b>C<sub>-3</sub></b>", és így tovább az százéves kormányos "<b>C<sub>-100</sub></b>"  jelét is (szerintünk a kormányos tízezer éves volna, de kinézetre csak százéves, ami érthető is: mozdulatai százszorosan le vannak lassítva és így százszor lasabban öregszik).<p>

Az űrhajó orra felé küldött ellenőrző "<b>C</b>"  vakuzás kétszáz év alatt éri utól a  legközelebbi egyéves csecsemőt, majd 200+10200 év elteltével a Földre érkezik a visszavert "<b>C<sub>+1</sub></b>" jel, további négyszáz év elteltével megérkezik a kétéves csecsemő "<b>C<sub>+2</sub></b>"  jele, majd legutoljára 20000+30000 év elteltével a Földre érkezik a visszavert "<b>C<sub>+100</sub></b>" jel a százéves legelülső emberről.

</body>
</html>


