<html><head><title>E0.EFIzika</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> </head>																	
<?php  include "../../h.php"; $_SERVER['REQUEST_URI']; $pa = $_SERVER['REQUEST_URI']; if (isset($_GET['pap']))				$pap = $_GET['pap']; if (isset($_GET['par']))				$par = $_GET['par']; ?> <body>								<tr>	
<table style="width: 100%;"><tbody><tr><td><a href="<?php  echo $hF; ?>@/8b.php"><img title="vissza" src="<?php  echo $hF; ?>@/01vissza.jpg" alt="vissza" border="0" /></a></td>																	
<td style="text-align: right;"><a href="<?php  echo $hF; ?>@/9a.php"> <img src="<?php  echo $hF; ?>@/02elore.jpg" alt="előre" /></a></td></tr></tbody></table>																	
<form action="<?php  echo $hF; ?>@/8c.php">																	
<table style="width: 100%;"> <tbody><tr><td><h2><a href="8c.php" >  8c Fizika: névsor / osztályzatok <small>s4h1</small></a><a href="<?php  echo $hF; ?>E0/E0FE.php">  <img  src="<?php  echo $hF; ?>@/00fel.jpg" title="Vissza a tankönyv/évfolyam-listához" alt="Vissza a tankönyv/évfolyam-listához" border="0" /></a></h2></td>																	
<td><h2 style="text-align: right;"> <a href="<?php  echo $hF; ?>in/inFE.php">  <img  src="<?php  echo $hF; ?>@/00fel.jpg" title="Bevezető megnyitása lassú hálózatban" alt="Bevezető megnyitása lassú hálózatban" border="0" /></a>  <a href="<?php  echo $hF; ?>in/index.php">Fizika egyszerűen</a> </h2> </td> </tr> </tbody> </table>																	
<table>	<input type="submit" value=">>">																
<td><?php   echo $a_megmaradás_törvényeX;?>	</td><td>	1	</td><td><?php $t1	=	'	Barna Bence	'; echo $t1	; ?>	</td><td>	5	</td><td>	<?php echo $n1	=	$_GET['n1	'] ; ?> </td><td>	<INPUT type="text" name="n1	" value="<?php echo $n1	; ?>" ></td></tr><tr>
<td><?php   echo $hol_van_a_kör_kezdeteX;?>	</td><td>	2	</td><td><?php $t2	=	'	Benkő Márton	'; echo $t2	; ?>	</td><td>	0	</td><td>	<?php echo $n2	=	$_GET['n2	'] ; ?> </td><td>	<INPUT type="text" name="n2	" value="<?php echo $n2	; ?>" ></td></tr><tr>
<td><?php   echo $cogito_ergo_sumX;?>	</td><td>	3	</td><td><?php $t3	=	'	Gáspár Koppány	'; echo $t3	; ?>	</td><td>	3 5	</td><td>	<?php echo $n3	=	$_GET['n3	'] ; ?> </td><td>	<INPUT type="text" name="n3	" value="<?php echo $n3	; ?>" ></td></tr><tr>
<td><?php   echo $Stephen_Hawking_Az_idő_rövid_története;?>	</td><td>	4	</td><td><?php $t4	=	'	Gombócz Aisa	'; echo $t4	; ?>	</td><td>	1 4	</td><td>	<?php echo $n4	=	$_GET['n4	'] ; ?> </td><td>	<INPUT type="text" name="n4	" value="<?php echo $n4	; ?>" ></td></tr><tr>
<td>	</td><td>	5	</td><td><?php $t5	=	'	Halla Petra Éva	'; echo $t5	; ?>	</td><td>	0	</td><td>	<?php echo $n5	=	$_GET['n5	'] ; ?> </td><td>	<INPUT type="text" name="n5	" value="<?php echo $n5	; ?>" ></td></tr><tr>
<td>	</td><td>	6	</td><td><?php $t6	=	'	Haraszti Levente Péter	'; echo $t6	; ?>	</td><td>	4	</td><td>	<?php echo $n6	=	$_GET['n6	'] ; ?> </td><td>	<INPUT type="text" name="n6	" value="<?php echo $n6	; ?>" ></td></tr><tr>
<td>	</td><td>	7	</td><td><?php $t7	=	'	Hoang Duc Anh	'; echo $t7	; ?>	</td><td>	2	</td><td>	<?php echo $n7	=	$_GET['n7	'] ; ?> </td><td>	<INPUT type="text" name="n7	" value="<?php echo $n7	; ?>" ></td></tr><tr>
<td>	</td><td>	8	</td><td><?php $t8	=	'	Hodászi Eszter	'; echo $t8	; ?>	</td><td>	5	</td><td>	<?php echo $n8	=	$_GET['n8	'] ; ?> </td><td>	<INPUT type="text" name="n8	" value="<?php echo $n8	; ?>" ></td></tr><tr>
<td>	</td><td>	9	</td><td><?php $t9	=	'	Horváth Márk	'; echo $t9	; ?>	</td><td>	5 5	</td><td>	<?php echo $n9	=	$_GET['n9	'] ; ?> </td><td>	<INPUT type="text" name="n9	" value="<?php echo $n9	; ?>" ></td></tr><tr>
<td>	</td><td>	10	</td><td><?php $t10	=	'	Kmetty Anna Száva	'; echo $t10	; ?>	</td><td>	4	</td><td>	<?php echo $n10	=	$_GET['n10	'] ; ?> </td><td>	<INPUT type="text" name="n10	" value="<?php echo $n10	; ?>" ></td></tr><tr>
<td>	</td><td>	11	</td><td><?php $t11	=	'	Kovács Zoltán	'; echo $t11	; ?>	</td><td>	5 5	</td><td>	<?php echo $n11	=	$_GET['n11	'] ; ?> </td><td>	<INPUT type="text" name="n11	" value="<?php echo $n11	; ?>" ></td></tr><tr>
<td>	</td><td>	12	</td><td><?php $t12	=	'	Kozsák László	'; echo $t12	; ?>	</td><td>	3	</td><td>	<?php echo $n12	=	$_GET['n12	'] ; ?> </td><td>	<INPUT type="text" name="n12	" value="<?php echo $n12	; ?>" ></td></tr><tr>
<td>	</td><td>	13	</td><td><?php $t13	=	'	Kucsa Brigitta Andrea	'; echo $t13	; ?>	</td><td>	3	</td><td>	<?php echo $n13	=	$_GET['n13	'] ; ?> </td><td>	<INPUT type="text" name="n13	" value="<?php echo $n13	; ?>" ></td></tr><tr>
<td>	</td><td>	14	</td><td><?php $t14	=	'	Lehoczki Fanni Mónika	'; echo $t14	; ?>	</td><td>	5	</td><td>	<?php echo $n14	=	$_GET['n14	'] ; ?> </td><td>	<INPUT type="text" name="n14	" value="<?php echo $n14	; ?>" ></td></tr><tr>
<td>	</td><td>	15	</td><td><?php $t15	=	'	Major Zoltán	'; echo $t15	; ?>	</td><td>	5 5	</td><td>	<?php echo $n15	=	$_GET['n15	'] ; ?> </td><td>	<INPUT type="text" name="n15	" value="<?php echo $n15	; ?>" ></td></tr><tr>
<td>	</td><td>	16	</td><td><?php $t16	=	'	Makkay Olivér	'; echo $t16	; ?>	</td><td>	5	</td><td>	<?php echo $n16	=	$_GET['n16	'] ; ?> </td><td>	<INPUT type="text" name="n16	" value="<?php echo $n16	; ?>" ></td></tr><tr>
<td>	</td><td>	17	</td><td><?php $t17	=	'	Németh Dominik	'; echo $t17	; ?>	</td><td>	5	</td><td>	<?php echo $n17	=	$_GET['n17	'] ; ?> </td><td>	<INPUT type="text" name="n17	" value="<?php echo $n17	; ?>" ></td></tr><tr>
<td>	</td><td>	18	</td><td><?php $t18	=	'	Németh Kristóf	'; echo $t18	; ?>	</td><td>	2	</td><td>	<?php echo $n18	=	$_GET['n18	'] ; ?> </td><td>	<INPUT type="text" name="n18	" value="<?php echo $n18	; ?>" ></td></tr><tr>
<td>	</td><td>	19	</td><td><?php $t19	=	'	Pap Alexandra	'; echo $t19	; ?>	</td><td>	2	</td><td>	<?php echo $n19	=	$_GET['n19	'] ; ?> </td><td>	<INPUT type="text" name="n19	" value="<?php echo $n19	; ?>" ></td></tr><tr>
<td>	</td><td>	20	</td><td><?php $t20	=	'	Ruszó Lídia Euniké	'; echo $t20	; ?>	</td><td>	0	</td><td>	<?php echo $n20	=	$_GET['n20	'] ; ?> </td><td>	<INPUT type="text" name="n20	" value="<?php echo $n20	; ?>" ></td></tr><tr>
<td>	</td><td>	21	</td><td><?php $t21	=	'	Varga Attila Pál	'; echo $t21	; ?>	</td><td>	0	</td><td>	<?php echo $n21	=	$_GET['n21	'] ; ?> </td><td>	<INPUT type="text" name="n21	" value="<?php echo $n21	; ?>" ></td></tr><tr>
</form>																	
<table style="width: 100%;"><tbody><tr><td><a href="<?php  echo $hF; ?>@/8b.php"><img title="vissza" src="<?php  echo $hF; ?>@/01vissza.jpg" alt="vissza" border="0" /></a></td>																	
<td style="text-align: right;"><a href="<?php  echo $hF; ?>@/9a.php"> <img src="<?php  echo $hF; ?>@/02elore.jpg" alt="előre" /></a></td></tr></tbody></table>																	
<?php include_once $pF . "100abc.php";?>  																	
