<?php  include "../../h.php"; $_SERVER['REQUEST_URI']; $pa = $_SERVER['REQUEST_URI']; if (isset($_GET['pap']))				$pap = $_GET['pap']; if (isset($_GET['par']))				$par = $_GET['par']; ?> <body>								<tr>	
<table style="width: 100%;"><tbody><tr><td><a href="<?php  echo $hF; ?>@/8c.php"><img title="vissza" src="<?php  echo $hF; ?>@/01vissza.jpg" alt="vissza" border="0" /></a></td>																	
<td style="text-align: right;"><a href="<?php  echo $hF; ?>@/9b.php"> <img src="<?php  echo $hF; ?>@/02elore.jpg" alt="előre" /></a></td></tr></tbody></table>																	
<form action="<?php  echo $hF; ?>@/9a.php">																	
<table style="width: 100%;"> <tbody><tr><td><h2><a href="9a.php" >  9a Fizika: névsor / osztályzatok <small>k1c3</small></a><a href="<?php  echo $hF; ?>E0/E0FE.php">  <img  src="<?php  echo $hF; ?>@/00fel.jpg" title="Vissza a tankönyv/évfolyam-listához" alt="Vissza a tankönyv/évfolyam-listához" border="0" /></a></h2></td>																	
<td><h2 style="text-align: right;"> <a href="<?php  echo $hF; ?>in/inFE.php">  <img  src="<?php  echo $hF; ?>@/00fel.jpg" title="Bevezető megnyitása lassú hálózatban" alt="Bevezető megnyitása lassú hálózatban" border="0" /></a>  <a href="<?php  echo $hF; ?>in/index.php">Fizika egyszerűen</a> </h2> </td> </tr> </tbody> </table>																	
<table>	<input type="submit" value=">>">																
<td><?php   echo $a_megmaradás_törvényeX;?>	</td><td>	1	</td><td><?php $t1	=	'	Bai Lilla Sarolta	'; echo $t1	; ?>	</td><td>	4	</td><td>	<?php echo $n1	=	$_GET['n1	'] ; ?> </td><td>	<INPUT type="text" name="n1	" value="<?php echo $n1	; ?>" ></td></tr><tr>
<td><?php   echo $hol_van_a_kör_kezdeteX;?>	</td><td>	2	</td><td><?php $t2	=	'	Bárány Kelemen Máté	'; echo $t2	; ?>	</td><td>	1 4 3	</td><td>	<?php echo $n2	=	$_GET['n2	'] ; ?> </td><td>	<INPUT type="text" name="n2	" value="<?php echo $n2	; ?>" ></td></tr><tr>
<td><?php   echo $cogito_ergo_sumX;?>	</td><td>	3	</td><td><?php $t3	=	'	Beleznay Soma	'; echo $t3	; ?>	</td><td>	1 3	</td><td>	<?php echo $n3	=	$_GET['n3	'] ; ?> </td><td>	<INPUT type="text" name="n3	" value="<?php echo $n3	; ?>" ></td></tr><tr>
<td><?php   echo $Stephen_Hawking_Az_idő_rövid_története;?>	</td><td>	4	</td><td><?php $t4	=	'	Berta Sára Boglárka	'; echo $t4	; ?>	</td><td>	4	</td><td>	<?php echo $n4	=	$_GET['n4	'] ; ?> </td><td>	<INPUT type="text" name="n4	" value="<?php echo $n4	; ?>" ></td></tr><tr>
<td>	</td><td>	5	</td><td><?php $t5	=	'	Bogdán Balázs Bence	'; echo $t5	; ?>	</td><td>	4	</td><td>	<?php echo $n5	=	$_GET['n5	'] ; ?> </td><td>	<INPUT type="text" name="n5	" value="<?php echo $n5	; ?>" ></td></tr><tr>
<td>	</td><td>	6	</td><td><?php $t6	=	'	Bujna Tamás József	'; echo $t6	; ?>	</td><td>	4 4	</td><td>	<?php echo $n6	=	$_GET['n6	'] ; ?> </td><td>	<INPUT type="text" name="n6	" value="<?php echo $n6	; ?>" ></td></tr><tr>
<td>	</td><td>	7	</td><td><?php $t7	=	'	Csajbók Éva	'; echo $t7	; ?>	</td><td>	3 5	</td><td>	<?php echo $n7	=	$_GET['n7	'] ; ?> </td><td>	<INPUT type="text" name="n7	" value="<?php echo $n7	; ?>" ></td></tr><tr>
<td>	</td><td>	8	</td><td><?php $t8	=	'	Farkas Dorottya	'; echo $t8	; ?>	</td><td>	5	</td><td>	<?php echo $n8	=	$_GET['n8	'] ; ?> </td><td>	<INPUT type="text" name="n8	" value="<?php echo $n8	; ?>" ></td></tr><tr>
<td>	</td><td>	9	</td><td><?php $t9	=	'	Gál Gergő Dániel	'; echo $t9	; ?>	</td><td>	4 4	</td><td>	<?php echo $n9	=	$_GET['n9	'] ; ?> </td><td>	<INPUT type="text" name="n9	" value="<?php echo $n9	; ?>" ></td></tr><tr>
<td>	</td><td>	10	</td><td><?php $t10	=	'	Gáspár Erik András	'; echo $t10	; ?>	</td><td>	3	</td><td>	<?php echo $n10	=	$_GET['n10	'] ; ?> </td><td>	<INPUT type="text" name="n10	" value="<?php echo $n10	; ?>" ></td></tr><tr>
<td>	</td><td>	11	</td><td><?php $t11	=	'	Győrffy Zsanett Júlia	'; echo $t11	; ?>	</td><td>	4	</td><td>	<?php echo $n11	=	$_GET['n11	'] ; ?> </td><td>	<INPUT type="text" name="n11	" value="<?php echo $n11	; ?>" ></td></tr><tr>
<td>	</td><td>	12	</td><td><?php $t12	=	'	Györki Tamás	'; echo $t12	; ?>	</td><td>	3	</td><td>	<?php echo $n12	=	$_GET['n12	'] ; ?> </td><td>	<INPUT type="text" name="n12	" value="<?php echo $n12	; ?>" ></td></tr><tr>
<td>	</td><td>	13	</td><td><?php $t13	=	'	Hajós Gergő Máté	'; echo $t13	; ?>	</td><td>	4	</td><td>	<?php echo $n13	=	$_GET['n13	'] ; ?> </td><td>	<INPUT type="text" name="n13	" value="<?php echo $n13	; ?>" ></td></tr><tr>
<td>	</td><td>	14	</td><td><?php $t14	=	'	Horváth Ákos	'; echo $t14	; ?>	</td><td>	1 3	</td><td>	<?php echo $n14	=	$_GET['n14	'] ; ?> </td><td>	<INPUT type="text" name="n14	" value="<?php echo $n14	; ?>" ></td></tr><tr>
<td>	</td><td>	15	</td><td><?php $t15	=	'	Juhász Márton	'; echo $t15	; ?>	</td><td>	4	</td><td>	<?php echo $n15	=	$_GET['n15	'] ; ?> </td><td>	<INPUT type="text" name="n15	" value="<?php echo $n15	; ?>" ></td></tr><tr>
<td>	</td><td>	16	</td><td><?php $t16	=	'	Kaczur András	'; echo $t16	; ?>	</td><td>	5 5	</td><td>	<?php echo $n16	=	$_GET['n16	'] ; ?> </td><td>	<INPUT type="text" name="n16	" value="<?php echo $n16	; ?>" ></td></tr><tr>
<td>	</td><td>	17	</td><td><?php $t17	=	'	Kaltenecker Lili Dorina	'; echo $t17	; ?>	</td><td>	3	</td><td>	<?php echo $n17	=	$_GET['n17	'] ; ?> </td><td>	<INPUT type="text" name="n17	" value="<?php echo $n17	; ?>" ></td></tr><tr>
<td>	</td><td>	18	</td><td><?php $t18	=	'	Kamrás Bence Botond	'; echo $t18	; ?>	</td><td>	4	</td><td>	<?php echo $n18	=	$_GET['n18	'] ; ?> </td><td>	<INPUT type="text" name="n18	" value="<?php echo $n18	; ?>" ></td></tr><tr>
<td>	</td><td>	19	</td><td><?php $t19	=	'	Kaszás Alexandra Vivien	'; echo $t19	; ?>	</td><td>	1 5	</td><td>	<?php echo $n19	=	$_GET['n19	'] ; ?> </td><td>	<INPUT type="text" name="n19	" value="<?php echo $n19	; ?>" ></td></tr><tr>
<td>	</td><td>	20	</td><td><?php $t20	=	'	Kelemen Franciska Anna	'; echo $t20	; ?>	</td><td>	3 4	</td><td>	<?php echo $n20	=	$_GET['n20	'] ; ?> </td><td>	<INPUT type="text" name="n20	" value="<?php echo $n20	; ?>" ></td></tr><tr>
<td>	</td><td>	21	</td><td><?php $t21	=	'	Kiss Vajk Bence	'; echo $t21	; ?>	</td><td>	3 5	</td><td>	<?php echo $n21	=	$_GET['n21	'] ; ?> </td><td>	<INPUT type="text" name="n21	" value="<?php echo $n21	; ?>" ></td></tr><tr>
<td>	</td><td>	22	</td><td><?php $t22	=	'	Lakatos Noémi Éva	'; echo $t22	; ?>	</td><td>	3	</td><td>	<?php echo $n22	=	$_GET['n22	'] ; ?> </td><td>	<INPUT type="text" name="n22	" value="<?php echo $n22	; ?>" ></td></tr><tr>
<td>	</td><td>	23	</td><td><?php $t23	=	'	Lengvárszky Petra	'; echo $t23	; ?>	</td><td>	4	</td><td>	<?php echo $n23	=	$_GET['n23	'] ; ?> </td><td>	<INPUT type="text" name="n23	" value="<?php echo $n23	; ?>" ></td></tr><tr>
<td>	</td><td>	24	</td><td><?php $t24	=	'	Nádas Virág	'; echo $t24	; ?>	</td><td>	0	</td><td>	<?php echo $n24	=	$_GET['n24	'] ; ?> </td><td>	<INPUT type="text" name="n24	" value="<?php echo $n24	; ?>" ></td></tr><tr>
<td>	</td><td>	25	</td><td><?php $t25	=	'	Nagy András	'; echo $t25	; ?>	</td><td>	4	</td><td>	<?php echo $n25	=	$_GET['n25	'] ; ?> </td><td>	<INPUT type="text" name="n25	" value="<?php echo $n25	; ?>" ></td></tr><tr>
<td>	</td><td>	26	</td><td><?php $t26	=	'	Papula Nóra	'; echo $t26	; ?>	</td><td>	3 4	</td><td>	<?php echo $n26	=	$_GET['n26	'] ; ?> </td><td>	<INPUT type="text" name="n26	" value="<?php echo $n26	; ?>" ></td></tr><tr>
<td>	</td><td>	27	</td><td><?php $t27	=	'	Pascal Áron Leon	'; echo $t27	; ?>	</td><td>	5 5	</td><td>	<?php echo $n27	=	$_GET['n27	'] ; ?> </td><td>	<INPUT type="text" name="n27	" value="<?php echo $n27	; ?>" ></td></tr><tr>
<td>	</td><td>	28	</td><td><?php $t28	=	'	Piller Barnabás	'; echo $t28	; ?>	</td><td>	5	</td><td>	<?php echo $n28	=	$_GET['n28	'] ; ?> </td><td>	<INPUT type="text" name="n28	" value="<?php echo $n28	; ?>" ></td></tr><tr>
<td>	</td><td>	29	</td><td><?php $t29	=	'	Székely Anna Flóra	'; echo $t29	; ?>	</td><td>	0	</td><td>	<?php echo $n29	=	$_GET['n29	'] ; ?> </td><td>	<INPUT type="text" name="n29	" value="<?php echo $n29	; ?>" ></td></tr><tr>
<td>	</td><td>	30	</td><td><?php $t30	=	'	Szendrei Csongor Csaba	'; echo $t30	; ?>	</td><td>	4 5	</td><td>	<?php echo $n30	=	$_GET['n30	'] ; ?> </td><td>	<INPUT type="text" name="n30	" value="<?php echo $n30	; ?>" ></td></tr><tr>
<td>	</td><td>	31	</td><td><?php $t31	=	'	Szlávicsek Emese	'; echo $t31	; ?>	</td><td>	5	</td><td>	<?php echo $n31	=	$_GET['n31	'] ; ?> </td><td>	<INPUT type="text" name="n31	" value="<?php echo $n31	; ?>" ></td></tr><tr>
<td>	</td><td>	32	</td><td><?php $t32	=	'	Tibor Tomaj Tamás	'; echo $t32	; ?>	</td><td>	0	</td><td>	<?php echo $n32	=	$_GET['n32	'] ; ?> </td><td>	<INPUT type="text" name="n32	" value="<?php echo $n32	; ?>" ></td></tr><tr>
<td>	</td><td>	33	</td><td><?php $t33	=	'	Ullrich Rebeka	'; echo $t33	; ?>	</td><td>	5	</td><td>	<?php echo $n33	=	$_GET['n33	'] ; ?> </td><td>	<INPUT type="text" name="n33	" value="<?php echo $n33	; ?>" ></td></tr><tr>
</form>																	
<table style="width: 100%;"><tbody><tr><td><a href="<?php  echo $hF; ?>@/8c.php"><img title="vissza" src="<?php  echo $hF; ?>@/01vissza.jpg" alt="vissza" border="0" /></a></td>																	
<td style="text-align: right;"><a href="<?php  echo $hF; ?>@/9b.php"> <img src="<?php  echo $hF; ?>@/02elore.jpg" alt="előre" /></a></td></tr></tbody></table>																	
<?php include_once $pF . "100abc.php";?>  																	
